version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-network
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - "mongodb_data:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - mongo-network
    ports:
      - 8081:8081
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongodb_data:
    driver: local

networks:
  mongo-network:
    name: mongo-network